Admin:
  resource: "@TitomePeintrePhilippeLerouxBundle/Resources/config/routing_admin.yml"
  prefix:   /admin
  
Accueil:
  pattern:  /
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Default:index }
  
Galerie:
  pattern:  /galerie
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Image:galerie }