AjoutImage:
  pattern:  /image/ajout
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Image:ajout }
  
AjoutCarousel:
  pattern:  /carousel/ajout
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Carousel:ajout }