AccueilAdmin:
  pattern:  /
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Default:admin }

AjoutImage:
  pattern:  /image/ajout
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Image:ajout }
  
ModifierImage:
  pattern:  /image/modification/{id}
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Image:modif }
  requirements:
    page: \d+
  
DeletePicture:
  pattern:  /image/supprimer/{id}
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Image:delete }
  requirements:
    page: \d+

AjoutCarousel:
  pattern:  /carousel/ajout
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Carousel:ajout }
  
OrdreCarousel:
  pattern:  /carousel/ordre
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Carousel:ordre }
  
ModifCarousel:
  pattern:  /carousel/modification/{id}
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Carousel:modif }
  requirements:
    page: \d+
    
DeleteViewCarousel:
  pattern:  /carousel/supprimer
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Carousel:deleteView }
  
DeleteCarousel:
  pattern:  /carousel/supprimer/{id}
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Carousel:delete }
  requirements:
    page: \d+