# Admin
AccueilAdmin:
  pattern:  /
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Default:admin }

# Image
AjoutImage:
  pattern:  /image/ajout
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Image:ajout }
  
ModifierImage:
  pattern:  /image/modification/{id}
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Image:modif }
  requirements:
    page: \d+
  
DeletePicture:
  pattern:  /image/supprimer/{id}
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Image:delete }
  requirements:
    page: \d+

# Carousel
AjoutCarousel:
  pattern:  /carousel/ajout
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Carousel:ajout }
  
OrdreCarousel:
  pattern:  /carousel/ordre
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Carousel:ordre }
  
ModifCarousel:
  pattern:  /carousel/modification/{id}
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Carousel:modif }
  requirements:
    page: \d+
    
DeleteViewCarousel:
  pattern:  /carousel/supprimer
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Carousel:deleteView }
  
DeleteCarousel:
  pattern:  /carousel/supprimer/{id}
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Carousel:delete }
  requirements:
    page: \d+
    
# Bio
ModifBio:
  pattern:  /biographie/modification
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Bio:ajout }
  
# Expo
ModifExpo:
  pattern:  /expositions/modification
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Expo:ajout }