Admin:
  resource: "@TitomePeintrePhilippeLerouxBundle/Resources/config/routing_admin.yml"
  prefix:   /admin

#TODO : Inclure le carousel dans le controleur Default avec la présentation sur la page d'accueil
Accueil:
  pattern:  /
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Carousel:index }
  
Galerie:
  pattern:  /galerie
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Image:galerie }
  
#TODO : À supprimer pour nettoyage
Inter:
  pattern : /c
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Default:inter }