Admin:
  resource: "@TitomePeintrePhilippeLerouxBundle/Resources/config/routing_admin.yml"
  prefix:   /admin
  
#TODO : Inclure le carousel dans le controleur Default avec la présentation sur la page d'accueil
Accueil:
  pattern:  /
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Carousel:index }
  
Galerie:
  pattern:  /galerie
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Image:galerie }
  
Bio:
  pattern:  /biographie
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Bio:index }
  
Expo:
  pattern:  /exposition
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Expo:index }