# Admin
AccueilAdmin:
  pattern:  /
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Default:admin }

# Image
AjoutImage:
  pattern:  /image/ajout
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Image:ajout }
  
ModifierImage:
  pattern:  /image/modification/{id}
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Image:modif }
  requirements:
    page: \d+
  
DeletePicture:
  pattern:  /image/supprimer/{id}
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Image:delete }
  requirements:
    page: \d+

# Carousel
AjoutCarousel:
  pattern:  /carousel/ajout
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Carousel:ajout }
  
OrdreCarousel:
  pattern:  /carousel/ordre
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Carousel:ordre }
  
ModifCarousel:
  pattern:  /carousel/modification/{id}
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Carousel:modif }
  requirements:
    id: \d+
    
DeleteViewCarousel:
  pattern:  /carousel/supprimer
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Carousel:deleteView }
  
DeleteCarousel:
  pattern:  /carousel/supprimer/{id}
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Carousel:delete }
  requirements:
    id: \d+
    
# Bio
ModifBio:
  pattern:  /biographie/modification
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Bio:ajout }
  
# Expo
ModifExpo:
  pattern:  /expositions/modification
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Expo:ajout }

# Actu
ModifActu:
  pattern:  /actualite/modification
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Actu:ajout }

# Livre
AjoutLivre:
  pattern:  /livre/ajout
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Livre:ajout }

ModifLivre:
  pattern:  /livre/modification/{id}
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Livre:modif }
  requirements:
    id: \d+
    
ModifLivreTitre:
  pattern:  /livre/modification/titre/{id}
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Livre:modifTitre }
  requirements:
    id: \d+
    
DeleteBook:
  pattern:  /livre/supprimer/{id}
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Livre:delete }
  requirements:
    id: \d+
    
AjoutPage:
  pattern:  /page/ajout/{livreId}
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Page:ajout }
  requirements:
    livreId:  \d+
    
DeleteViewPage:
  pattern:  /page/supprimer/{livreId}
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Page:deleteView }
  requirements:
    livreId:  \d+
    
DeletePage:
  pattern:  /page/supprimer/{livreId}/{id}
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Page:delete }
  requirements:
    livreId:  \d+
    id: \d+