AccueilAdmin:
  pattern:  /
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Default:admin }

AjoutImage:
  pattern:  /image/ajout
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Image:ajout }
  
ModifierImage:
  pattern:  /image/modification/{id}
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Carousel:modif }
  requirements:
    page: \d+
  
DeletePicture:
  pattern:  /image/supprimer/{id}
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Image:delete }
  requirements:
    page: \d+

AjoutCarousel:
  pattern:  /carousel/ajout
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Carousel:ajout }