Admin:
  resource: "@TitomePeintrePhilippeLerouxBundle/Resources/config/routing_admin.yml"
  prefix:   /admin
  
#TODO : Inclure le carousel dans le controleur Default avec la présentation sur la page d'accueil
Accueil:
  pattern:  /
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Carousel:index }
  
Galerie:
  pattern:  /galerie
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Image:galerie }
  
Bio:
  pattern:  /biographie
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Bio:index }
  
# EXPO
#Expo:
#  pattern:  /exposition
#  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Expo:index }

Actu:
  pattern:  /actualite
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Actu:index }

# Contact
Contact:
  pattern:  /contact
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Contact:index }

ContactPeintre:
  pattern:  /contact/peintre
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Contact:peintre }

ContactGestionnaire:
  pattern:  /contact/gestionnaire
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Contact:gestionnaire }

# Livre
Livre:
  pattern:  /livre
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Livre:index }

LireLivre:
  pattern:  /livre/lire/{id}
  defaults: { _controller: TitomePeintrePhilippeLerouxBundle:Page:index }
  requirements:
    id:  \d+