imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    default_locale: %locale%
    #esi:             ~
    translator:      { fallback: %locale% }
    trust_proxy_headers: false
    secret:          %secret%
    #charset:         UTF-8
    router:          
      resource: "%kernel.root_dir%/config/routing.yml"
      strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:  ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    bundles: [TitomePeintrePhilippeLerouxBundle]
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    spool: { type: memory }
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    
avalanche_imagine:
    filters:
        # Lors de la création d'un nouveau filtre,  penser à rajouter un moyen de supprimer l'image créée dans la méthode
        # deleteAction du contrôleur ImageController
        my_thumb:
            type:    thumbnail
            options: { size: [400, 400], mode: inset }
        img:
          type:    thumbnail
          options: { size: [800, 800], mode: inset }

fos_user:
    db_driver:     orm                        # Le type de BDD à utiliser, nous utilisons l'ORM Doctrine depuis le début
    firewall_name: main                       # Le nom du firewall duquel on utilisera ces utilisateurs
    user_class:    Titome\UserBundle\Entity\User # La classe de l'entité User que nous venons de définir
    
trsteel_ckeditor:
    toolbar: ['document', 'clipboard', 'editing', '/', 'basicstyles', 'paragraph', 'links', '/', 'insert', 'styles', 'colors', 'tools']
    toolbar_groups:
        colors: ['TextColor', 'BGColor']
    filebrowser_browse_url: "/peintrephilippeleroux/web/bundles/titomepeintrephilippeleroux/kcfinder/browse.php?type=files"
    filebrowser_upload_url: "/peintrephilippeleroux/web/bundles/titomepeintrephilippeleroux/kcfinder/upload.php?type=files"
    filebrowser_image_browse_url: "/peintrephilippeleroux/web/bundles/titomepeintrephilippeleroux/kcfinder/browse.php?type=images"
    filebrowser_image_upload_url: "/peintrephilippeleroux/web/bundles/titomepeintrephilippeleroux/kcfinder/upload.php?type=images"
    filebrowser_flash_browse_url: "/peintrephilippeleroux/web/bundles/titomepeintrephilippeleroux/kcfinder/browse.php?type=flash"
    filebrowser_flash_upload_url: "/peintrephilippeleroux/web/bundles/titomepeintrephilippeleroux/kcfinder/upload.php?type=flash"