<?php

namespace Titome\PeintrePhilippeLerouxBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
    public function listeGalerie()
    {
        $qb = $this->createQueryBuilder('i');
        
        $qb->orderBy('i.ordre', 'DESC');
        
        return $qb->getQuery()->getResult();
    }
}